export const theme = {
    colors: {
        primary: '#0052D4',
        secondary: '#4364F7',
        accent: '#6FB1FC',
        success: '#00C853',
        warning: '#FFAB00',
        danger: '#D50000',
        background: '#F8FAFC',
        surface: '#FFFFFF',
        text: '#1E293B',
        textLight: '#64748B',
        border: '#E2E8F0',
        cardBlue: '#4A90E2',
        cardGreen: '#50C878',
        cardOrange: '#FFA500',
        cardCoral: '#FF7F50',
    },
    spacing: {
        xs: 4,
        sm: 8,
        md: 16,
        lg: 24,
        xl: 32,
    },
    borderRadius: {
        sm: 4,
        md: 8,
        lg: 12,
        xl: 20,
        round: 50,
    },
    shadows: {
        xs: {
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 1 },
            shadowOpacity: 0.05,
            shadowRadius: 1,
            elevation: 1,
        },
        sm: {
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 1 },
            shadowOpacity: 0.1,
            shadowRadius: 2,
            elevation: 2,
        },
        md: {
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: 0.1,
            shadowRadius: 6,
            elevation: 4,
        },
        lg: {
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 10 },
            shadowOpacity: 0.15,
            shadowRadius: 12,
            elevation: 8,
        },
    },
};
